name: Deploy to Netlify

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write
  deployments: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: ${{ steps.deploy.outputs.url }}
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Check Required Secrets
        run: |
          if [ -z "${{ secrets.VITE_SUPABASE_ANON_KEY }}" ]; then
            echo "Error: VITE_SUPABASE_ANON_KEY is not set in repository secrets"
            exit 1
          fi
          if [ -z "${{ secrets.NETLIFY_AUTH_TOKEN }}" ]; then
            echo "Error: NETLIFY_AUTH_TOKEN is not set in repository secrets"
            exit 1
          fi
          if [ -z "${{ secrets.NETLIFY_SITE_ID }}" ]; then
            echo "Error: NETLIFY_SITE_ID is not set in repository secrets"
            exit 1
          fi

      - name: Create env file
        run: |
          cat << EOF > .env
          VITE_SUPABASE_URL=https://bvmzjtwvwmjksrjnjbry.supabase.co
          VITE_SUPABASE_ANON_KEY=${{ secrets.VITE_SUPABASE_ANON_KEY }}
          EOF

      - name: Lint
        run: npm run lint
      
      - name: Build
        env:
          VITE_SUPABASE_URL: https://bvmzjtwvwmjksrjnjbry.supabase.co
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        run: npm run build

      - name: Deploy to Netlify
        id: deploy
        if: github.ref == 'refs/heads/main'
        uses: nwtgck/actions-netlify@v2.0
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          publish-dir: './dist'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        timeout-minutes: 5
